# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9.7.1

pipelines:
  branches:
    staging:
      - step:
          caches:
            - node
            - globalnode
            - localnode
          script: # Modify the commands below to build your repository.
            - node scripts/deployconfig-staging
            - cat .env
            - cat .firebaserc
            - cat firebase.json
            - yarn global add firebase-tools
            - yarn install
            - CI=false yarn build
            - firebase deploy --token "$FIREBASE_TOKEN" --only hosting
    production:
      - step:
          caches:
            - node
            - globalnode
            - localnode
          script: # Modify the commands below to build your repository.
            # Run script to write config files
            - node scripts/deployconfig-production
            # Add bit repo authentication
            - echo "//node.bit.dev/:_authToken = $BIT_NODE_TOKEN_INFO2HATS" >> .npmrc
            # Verify files are correct
            - cat .env
            - cat .firebaserc
            - cat firebase.json
            # Install dependencies
            - yarn global add firebase-tools
            - yarn install
            # Build
            - CI=false yarn build
            # Deploy to hosting
            - firebase deploy --token "$FIREBASE_TOKEN" --only hosting
definitions:
  caches:
    globalnode: /usr/local/lib/node_modules
    localnode: /opt/atlassian/pipelines/agent/build/functions/node_modules
