export const COLLECTIONS = {
  users: 'users',
  candidates: 'candidates',
  submissions: 'submissions',
  upcomingEvents: 'upcomingEvents',
  profiles: 'profiles',
  emailVerifications: 'emailVerifications',
  smartLinks: 'smartLinks',
  remoteLogs: 'remoteLogs',
  bugReports: 'bugReports',
  charts: 'charts',
  messages: 'messages',
  admins: 'admins',
  linkedinClients: 'linkedinClients',
  linkedinCampaigns: 'linkedinCampaigns',
  linkedinMessageQueue: 'linkedinMessageQueue',
  communications: 'communications',
  conversations: 'conversations',
  gmailOutbox: 'gmailOutbox',
};
