export const trackers = {
  signup: {
    presetName: 'signup',
    type: 'candidate',
    name: 'signup',
    label: 'Sign ups',
    itemType: 'tracker',
  },
  signup3rdParty: {
    presetName: 'signup3rdParty',
    type: 'candidate',
    name: 'signup-3rdParty',
    label: '3rd party sign ups',
    itemType: 'tracker',
  },
  signupPassword: {
    presetName: 'signupPassword',
    type: 'candidate',
    name: 'signup-password',
    label: 'Password sign ups',
    itemType: 'tracker',
  },
  signupSpeedy: {
    presetName: 'signupSpeedy',
    type: 'candidate',
    name: 'signup-speedy',
    label: 'Speedy sign ups',
    itemType: 'tracker',
  },
  submission: {
    presetName: 'submission',
    type: 'candidate',
    name: 'submission',
    label: 'Submissions',
    itemType: 'tracker',
  },
  discussionGroup: {
    presetName: 'discussionGroup',
    type: 'link',
    name: 'DiscussionGroup',
    label: 'Discussion Group links',
    itemType: 'tracker',
  },
  submissionAccepted: {
    presetName: 'submissionAccepted',
    type: 'talentTeam',
    name: 'submissionAccepted',
    label: 'Accepted submissions',
    itemType: 'tracker',
  },
  // submissionProcessed: { type:'talentTeam', name:'submissionProcessed', label:'Processed submissions', itemType:'tracker' },
  submissionRejected: {
    presetName: 'submissionRejected',
    type: 'talentTeam',
    name: 'submissionRejected',
    label: 'Rejected submissions',
    itemType: 'tracker',
  },
  // submissionReviewed: { type:'talentTeam', name:'submissionReviewed', label:'Reviewed submissions', itemType:'tracker' },
  // submissionFeedbacked: { type:'talentTeam', name:'feedbacked', label:'Feedbacked submissions', itemType:'tracker' },
  assessmentAccepted: {
    presetName: 'assessmentAccepted',
    type: 'talentTeam',
    name: 'assessmentAccepted',
    label: 'Accepted assements',
    itemType: 'tracker',
  },
  assessmentRejected: {
    presetName: 'assessmentRejected',
    type: 'talentTeam',
    name: 'assessmentRejected',
    label: 'Rejected assements',
    itemType: 'tracker',
  },
  interviewAccepted: {
    presetName: 'interviewAccepted',
    type: 'talentTeam',
    name: 'interviewAccepted',
    label: 'Accepted interviews',
    itemType: 'tracker',
  },
  interviewRejected: {
    presetName: 'interviewRejected',
    type: 'talentTeam',
    name: 'interviewRejected',
    label: 'Rejected interviews',
    itemType: 'tracker',
  },
  feedbacked: {
    presetName: 'feedbacked',
    type: 'me',
    name: 'feedbacked',
    label: 'Feedbacked by you',
    itemType: 'tracker',
  },
  toBeFeedbacked: {
    presetName: 'toBeFeedbacked',
    label: 'to be feedbacked',
    filters: [
      { property: 'outcome', operation: '==', value: 'rejected' },
      { property: 'feedbacked', operation: '==', value: false },
    ],
    collection: 'submissions',
    itemType: 'query',
  },
  toBeInvited: {
    presetName: 'toBeInvited',
    label: 'to be invited',
    filters: [
      { property: 'outcome', operation: '==', value: 'accepted' },
      { property: 'feedbacked', operation: '==', value: false },
    ],
    collection: 'submissions',
    itemType: 'query',
  },
  toBeScreened: {
    presetName: 'toBeScreened',
    label: 'to be screened',
    filters: [{ property: 'outcome', operation: '==', value: 'pending' }],
    collection: 'submissions',
    itemType: 'query',
  },

  interestJobs: {
    presetName: 'interestJobs',
    label: 'interested in jobs',
    filters: [{ property: 'interest', operation: '==', value: 'jobs' }],
    collection: 'users',
    itemType: 'query',
  },
  interestCourses: {
    presetName: 'interestCourses',
    label: 'interested in courses',
    filters: [{ property: 'interest', operation: '==', value: 'courses' }],
    collection: 'users',
    itemType: 'query',
  },
  interestAssessments: {
    presetName: 'interestAssessments',
    label: 'interested in assessments',
    filters: [{ property: 'interest', operation: '==', value: 'assessments' }],
    collection: 'users',
    itemType: 'query',
  },

  jobApplied: {
    presetName: 'jobApplied',
    type: 'candidate',
    name: 'job-applied',
    label: 'Job applications',
    itemType: 'tracker',
  },
  jobScreened: {
    presetName: 'jobScreened',
    type: 'job',
    name: 'job-screened',
    label: 'Job applications screened',
    itemType: 'tracker',
  },
  jobPass: {
    presetName: 'jobPass',
    type: 'job',
    name: 'job-pass',
    label: 'Job applications passed',
    itemType: 'tracker',
  },
  jobFail: {
    presetName: 'jobFail',
    type: 'job',
    name: 'job-fail',
    label: 'Job applications failed',
    itemType: 'tracker',
  },

  assessmentStarted: {
    presetName: 'assessmentStarted',
    type: 'assessment',
    name: 'assessment-started',
    label: 'Assessments started',
    itemType: 'tracker',
  },
  assessmentSubmitted: {
    presetName: 'assessmentSubmitted',
    type: 'assessment',
    name: 'assessment-submitted',
    label: 'Assessment submissions',
    itemType: 'tracker',
  },
  assessmentScreened: {
    presetName: 'assessmentScreened',
    type: 'assessment',
    name: 'assessment-screened',
    label: 'Assessments screened',
    itemType: 'tracker',
  },
  assessmentPass: {
    presetName: 'assessmentPass',
    type: 'assessment',
    name: 'assessment-pass',
    label: 'Assessments passed',
    itemType: 'tracker',
  },
  assessmentFail: {
    presetName: 'assessmentFail',
    type: 'assessment',
    name: 'assessment-fail',
    label: 'Assessments failed',
    itemType: 'tracker',
  },

  courseCompleted: {
    presetName: 'courseCompleted',
    type: 'courses',
    name: 'course-completed',
    label: 'Course completions',
    itemType: 'tracker',
  },
};

export const trackersList = Object.keys(trackers).map(x => ({
  name: x,
  itemType: trackers[x].itemType,
  label: trackers[x].label,
}));
