export const UNIVERSITIES = [
  `University of Sydney\u2063 (USYD)`,
  `University of New South Wales\u2063 (UNSW)`,
  `Macquarie University\u2063 (MQ)`,
  `University of Technology Sydney\u2063 (UTS)`,
  `Western Sydney University\u2063 (WSU)`,
  `University of Notre Dame\u2063 (UND)`,
  `University of Wollongong\u2063 (UW)`,
  `University of Newcastle\u2063 (UN)`,
  `Australian Catholic University\u2063 (ACU)`,
  `Harvard University`,
  `Massachusetts Institute of Technology\u2063 (MIT)`,
  `University of California--Berkeley`,
  `Stanford University`,
  `University of Oxford`,
  `University of Cambridge`,
  `California Institute of Technology`,
  `University of California--Los Angeles`,
  `University of Chicago`,
  `Columbia University`,
  `Johns Hopkins University`,
  `Imperial College London`,
  `Princeton University`,
  `University of Michigan`,
  `University of Toronto`,
  `University of Washington`,
  `Yale University`,
  `University of California--San Diego`,
  `University of Pennsylvania`,
  `Duke University`,
  `University College London`,
  `University of California--San Francisco`,
  `Cornell University`,
  `University of Tokyo`,
  `Northwestern University`,
  `Swiss Federal Institute of Technology Zurich`,
  `University of Wisconsin--Madison`,
  `University of California--Santa Barbara`,
  `University of Minnesota--Twin Cities`,
  `University of British Columbia`,
  `University of Texas--Austin`,
  `University of Melbourne`,
  `University of North Carolina--Chapel Hill`,
  `Ohio State University`,
  `University of Illinois Urbana-Champaign`,
  `New York University`,
  `Boston University`,
  `University of California--Davis`,
  `Peking University`,
  `University of Edinburgh`,
  `Washington University`,
  `University of Hong Kong`,
  `University of Pittsburgh`,
  `McGill University`,
  `Pierre and Marie Curie University - Paris 6`,
  `University of Queensland Australia`,
  `University of Munich`,
  `University of Manchester`,
  `University of Southern California`,
  `University of Maryland--College Park`,
  `Pennsylvania State University`,
];
